spring:
  application:
    name: survey-response-gateway
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local

---

spring:
  application:
    name: survey-response-gateway
  config:
    import: optional:configserver:http://{CONFIG_SERVER_HOST}:8080
    activate:
      on-profile: dev