server:
  port: 10000
spring:
  application:
    name: survey-admin-service

  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/admin
      username: survey
      password: survey12!@
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret-key: mNg2HmZ+PLALRs2Q6t6AZupdKDSXTOUikLt4dHwIWmHxW047aQRzg4xMBCY9r8li
  expire:
    access-token: 60 * 5
    refresh-token: 60 * 60 * 24 * 30