version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_survey
    environment:
      POSTGRES_USER: survey         # 사용자 이름
      POSTGRES_PASSWORD: survey12!@  # 비밀번호
    ports:
      - "5432:5432"                 # 호스트와 컨테이너의 포트 매핑
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 데이터 영속성 유지
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
volumes:
  redis-data:
  postgres_data:
