spring:
  application:
    name: survey

  datasource:
    url: jdbc:postgresql://localhost:5432/survey
    hikari:
      driver-class-name: org.postgresql.Driver
      username: survey
      password: survey12!@

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
