server:
  port: 10001

spring:
  application:
    name: survey-respondent-service
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/respondent
      driver-class-name: org.postgresql.Driver
      username: survey
      password: survey12!@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true

  config:
    import: social.yml
    
  cloud:
    openfeign:
      client:
        config:
          googleFeignClient:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


